// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtqAouDd8KdsSj0huOfyp_Vjw7ZBb-TM',
    appId: '1:587646196458:web:40f7022583e53135fe9593',
    messagingSenderId: '587646196458',
    projectId: 'fir-19312078',
    authDomain: 'fir-19312078.firebaseapp.com',
    storageBucket: 'fir-19312078.appspot.com',
    measurementId: 'G-PT9BKHDDEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKuOeJ_M1-sz9NQYN24Dd18-WU95UMWU',
    appId: '1:587646196458:android:213b27205b9460e8fe9593',
    messagingSenderId: '587646196458',
    projectId: 'fir-19312078',
    storageBucket: 'fir-19312078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBleTn-KefWWkxX4oJI9-LU1L4_6iCMReo',
    appId: '1:587646196458:ios:8c366be04da9b7d7fe9593',
    messagingSenderId: '587646196458',
    projectId: 'fir-19312078',
    storageBucket: 'fir-19312078.appspot.com',
    iosClientId:
        '587646196458-vijldtifadq3lp815hjhljmsqlmeee1s.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBleTn-KefWWkxX4oJI9-LU1L4_6iCMReo',
    appId: '1:587646196458:ios:95a37457678888d6fe9593',
    messagingSenderId: '587646196458',
    projectId: 'fir-19312078',
    storageBucket: 'fir-19312078.appspot.com',
    iosClientId:
        '587646196458-2di9mfu70f83anmiqc3pd1d86mfu30bg.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet.RunnerTests',
  );
}
